parameters:
  ContactId:
    name: contactId
    in: path
    required: true
    description: Mongo ObjectId контакту
    schema:
      type: string
      example: 66cfc8f2b7d1a4e0b2a9f9c1

  Page:
    name: page
    in: query
    description: Номер сторінки (1..N)
    schema:
      type: integer
      minimum: 1
      default: 1

  Limit:
    name: limit
    in: query
    description: Кількість на сторінку
    schema:
      type: integer
      minimum: 1
      maximum: 100
      default: 20

  Favorite:
    name: favorite
    in: query
    description: Фільтр улюблених
    schema:
      type: boolean

  Sort:
    name: sort
    in: query
    description: Поле сортування (з '-' для DESC)
    schema:
      type: string
      enum: [name, -name, createdAt, -createdAt]
