ContactId:
  name: contactId
  in: path
  required: true
  schema:
    type: string
    example: 66cfc8f2b7d1a4e0b2a9f9c1

Page:
  name: page
  in: query
  required: false
  schema:
    type: integer
    default: 1
    example: 1

Limit:
  name: limit
  in: query
  required: false
  schema:
    type: integer
    default: 20
    example: 20

Favorite:
  name: favorite
  in: query
  required: false
  schema:
    type: boolean
    example: true

Sort:
  name: sort
  in: query
  required: false
  schema:
    type: string
    enum: [asc, desc]
    default: asc
    example: asc