openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact Management API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API для управления контактами с аутентификацией пользователей
tags:
  - name: Contacts
    description: Операции с контактами
  - name: Auth
    description: Аутентификация пользователей
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-pfm6.onrender.com
paths:
  /contacts/{id}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    ApiResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: Operation completed successfully
        data:
          type: object
          nullable: true
    Contact:
      type: object
      properties:
        id:
          type: string
          description: Уникальный идентификатор контакта
        name:
          type: string
          description: Имя контакта
        email:
          type: string
          format: email
          description: Email адрес
        phone:
          type: string
          description: Номер телефона
        favorite:
          type: boolean
          description: Флаг избранного контакта
          default: false
        owner:
          $ref: '#/components/schemas/User'
      required:
        - name
        - email
        - phone
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        subscription:
          type: string
          enum: [starter, pro, business]
          default: starter
    ContactList:
      type: object
      properties:
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/Contact'
        total:
          type: integer
          example: 100
        page:
          type: integer
          example: 1
        limit:
          type: integer
          example: 10
  responses:
    UnauthorizedError:
      description: Не авторизован
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'
            properties:
              status:
                type: string
                example: error
              message:
                type: string
                example: Not authorized
    NotFoundError:
      description: Ресурс не найден
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'
            properties:
              status:
                type: string
                example: error
              message:
                type: string
                example: Not found
    ValidationError:
      description: Ошибка валидации
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'
            properties:
              status:
                type: string
                example: error
              message:
                type: string
                example: Validation error
              details:
                type: array
                items:
                  type: object
                  properties:
                    path:
                      type: string
                    message:
                      type: string