openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact Management API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API для управления контактами с аутентификацией пользователей
tags:
  - name: Contacts
    description: Операции с контактами
  - name: Auth
    description: Аутентификация пользователей
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-pfm6.onrender.com
paths:
  /contacts/{id}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register/post.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login/post.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout/post.yaml'
  /auth/current:
    get:
      $ref: '../swagger/paths/auth/current/get.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Contact:
      $ref: '../swagger/components/schemas/Contact.yaml'
    User:
      $ref: '../swagger/components/schemas/User.yaml'
    AuthResponse:
      $ref: '../swagger/components/schemas/AuthResponse.yaml'
  responses:
    UnauthorizedError:
      $ref: '../swagger/components/responses/UnauthorizedError.yaml'
    NotFoundError:
      $ref: '../swagger/components/responses/NotFoundError.yaml'
    ValidationError:
      $ref: '../swagger/components/responses/ValidationError.yaml'